apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mtg4
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-mtg4@sha256:4a2b080936a64d9745b8bb613475c5e0552b7d8ea31873110d8e358d281d957c
        name: my-nodejs
        resources: {}
status: {}
